# Generated by Django 4.2.20 on 2025-05-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanges", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="exchangeproposal",
            constraint=models.CheckConstraint(
                check=models.Q(("ad_sender", models.F("ad_receiver")), _negated=True),
                name="ad_sender_not_equal_ad_receiver",
                violation_error_message="Объявления отправителя и получателя не могут быть одинаковыми.",
            ),
        ),
    ]
