volumes:
  pg_data:
  static:
  media:

services:

  psql:
    image: postgres:latest
    container_name: sharings_db
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  sharings_backend:
    build: ../src
    container_name: sharings_backend
    env_file: ../.env
    ports:
      - "8008:8008"
    depends_on:
      - psql
    volumes:
      - static:/app/static
      - media:/app/media



