# Generated by Django 4.2.20 on 2025-05-21 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        verbose_name="Уникальный идентификатор категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория объявления",
                "verbose_name_plural": "Категории объявлений",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Заголовок объявления"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание объявления"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на изображение",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "Новое"), ("used", "Б/У")],
                        default="new",
                        max_length=10,
                        verbose_name="Состояние товара",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания объявления",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads.category",
                        verbose_name="Категория объявления",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор объявления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ("-created_at",),
                "default_related_name": "ads",
                "indexes": [
                    models.Index(fields=["user"], name="user_idx"),
                    models.Index(fields=["category"], name="category_idx"),
                ],
            },
        ),
    ]
