# Generated by Django 4.2.20 on 2025-05-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="image_url",
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Ссылка на изображение",
            ),
        ),
    ]
