# Generated by Django 4.2.20 on 2025-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="image_url",
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Изображение объявления",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="is_exchanged",
            field=models.BooleanField(default=False, verbose_name="Обменено"),
        ),
    ]
