# Generated by Django 4.2.20 on 2025-05-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_remove_ad_image_url_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Изображение объявления",
            ),
        ),
    ]
