# Generated by Django 4.2.20 on 2025-05-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_exchanged",
            field=models.BooleanField(default=False, verbose_name="Обменено"),
        ),
    ]
