# Ads constants
AD_TITLE_LENGTH = 100
CONDITION_CHOICE_LENGTH = 10

# Category constants
CATEGORY_TITLE_LENGTH = 100
CATEGORY_SLUG_LENGTH = 100
CATEGORY_SLUG_ADDON = 6

# Exchange constants
EXCHANGE_TITLE_LENGTH = 100
EXCHANGE_STATUS_LENGTH = 10


# User constants
